######################################################################
# Automatically generated by qmake (2.01a) mer. oct. 15 10:08:09 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Calcul.h Intro.h MainWindow.h
FORMS += MainWindow.ui
SOURCES += Calcul.cpp Intro.cpp main.cpp MainWindow.cpp
