CV-BARAT.pdf: CV-BARAT.tex
	pdflatex CV-BARAT.tex

clean:proper
	@echo «suppression des pdfs»
	@rm -f *.pdf
proper:
	@echo «suppression des fichiers de compilation»
	@rm -f *.log *.aux *.dvi *.toc *.lot *.lof *.out