######################################################################
# Automatically generated by qmake (2.01a) jeu. oct. 16 07:56:11 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MyQWidget.h
SOURCES += demo.cpp MyQWidget.cpp
